name = "ArrhythmRelations"
uuid = "a2daa527-c2e6-4085-b47f-8980de360814"
version = "1.0.0-DEV"
authors = ["Razheva Elena <razh348@gmail.com> and contributors"]

[deps]
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Descriptors = "b2dd10be-c0b5-41fc-bf7d-fdb86be5b335"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FileUnv_jll = "c10d0ea1-10c0-5fab-a796-b821f293b8d8"
FileUtils = "61402b12-eb4b-4f0c-a04f-adfcfe5d14e4"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IBoxAccess = "1607262a-405a-4f9a-89bc-45a61e12db11"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
TimeSamplings = "ed45db17-24e9-469d-8275-17d3d36e28e6"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"
XMLDict = "228000da-037f-5747-90a9-8195ccbf91a5"
wfdb_wrapper_jll = "cfa65b43-6878-5963-b59c-e7edc60d5dc9"

[sources]
Descriptors = {url = "https://github.com/IncartStudents/Descriptors.jl"}
FileUnv_jll = {url = "https://github.com/a-mikhaylov/FileUnv_jll.jl.git"}
IBoxAccess = {url = "https://github.com/IncartStudents/IBoxAccess.jl"}
TimeSamplings = {url = "https://github.com/IncartStudents/TimeSamplings.jl"}
wfdb_wrapper_jll = {url = "https://github.com/sairus7/wfdb_wrapper_jll.jl.git"}

[compat]
DSP = "0.8.4"
Distributions = "0.25.123"
FileUtils = "1.0.12"
HypothesisTests = "0.11.6"
OrderedCollections = "1.8.1"
Printf = "1.11.0"
Random = "1.11.0"
XLSX = "0.10.4"
XMLDict = "0.4.1"
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
