name = "ArythmRelations"
uuid = "a2daa527-c2e6-4085-b47f-8980de360814"
authors = ["Razheva Elena <razh348@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
